### ISSUE TITLE
An operation error for interatomic potential

### ISSUE THREAD

**Issue by Shiliang2333** [shuozhixu/APLmater_2022#1]
Dear Xu,
I used interatomic potential "HfNbTaTiZr_Xu2022.eam.alloy" to conduct a simulation,and the software reports an error with"Not a valid integer number: '<!DOCTYPE'".I checked the potential file and found that the content format seems to be different from the general eam/alloy file.Is the potential file updated or what precautions should be taken when using it?Hope to get your reply,thanks!
Han

**Comment by shuozhixu** [comment]
I could not reproduce the error. My simulation ran well with this potential file. I did find a [post](https://matsci.org/t/error-of-not-a-valid-integer/40523) for a similar issue. Please take a look.

**Comment by Shiliang2333** [comment]
> I could not reproduce the error. My simulation ran well with this potential file. I did find a [post](https://matsci.org/t/error-of-not-a-valid-integer/40523) for a similar issue. Please take a look.

I got this!
When I use the "Save Link As" command to download the potential file, I will get an error result, which is only 202KB in size.However, when I click the file link and view it using the web browser, the file content is correct, and its size is 1.23MB.What a strange phenomenon! I often use the "Save Link As" command to download files,and it works very well.Thank you very much for your check and reply,Xu.I hope this post is useful to later comers.
